[package]
name = "plotter-rs"
version = "0.1.0"
authors = ["Jonathan Nilsson"]

[dependencies]
arrayvec = "0.4.7"
crossbeam = "0.3.0"
glium = { version = "0.19", default-features = true }
glutin = "0.11"
imgui = { version = "0.0.18" }
imgui-glium-renderer = { version = "0.0.18" }
imgui-sys = { version = "0.0.18", features = ["glium"] }
nfd = "0.0.4"
rand = "0.4.2"
time = "0.1.39"