[package]
name = "plotter-rs"
version = "0.1.0"
authors = ["Jonathan"]

[dependencies]
glium = { version = "0.19", default-features = true }
glutin = "0.11"
imgui = { version = "0.0.18" }
imgui-glium-renderer = { version = "0.0.18" }
imgui-sys = { version = "0.0.18", features = ["glium"] }
